# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

format = '$all'

[hostname]
ssh_only = false
style = 'fg:#ff0000'
format = '[$ssh_symbol$hostname]($style) in '
disabled = false

[localip]
ssh_only = false
disabled = false

[git_branch]
symbol = 'ğŸŒ± '
truncation_length = 4
truncation_symbol = ''


[directory]
truncate_to_repo = true
style = 'fg:#00bfff'
[conda]
disabled = false
format = '[$symbol$environment](dimmed green) '

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = 'fg:#228b22'
# ~/.config/starship.toml

[time]
style = 'fg:#ffc0cb'
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = '%T'
# ~/.config/starship.toml

[package]
format = 'via [ğŸ $version](208 bold) '
